mainapp/urls.py
from django.urls import path, include

from .views import *


urlpatterns = [
    path('', home, name='home'),
    path('view/', view, name='view'),
    path('products/<str:slug>/', product_view, name='product_detail'),
    path('category/<str:slug>/', category_view, name='category_detail'),
    path('sub_category/<str:slug>/', sub_category_view, name='sub_category_detail'),
    path('cart/', cart_view, name='cart'),
    path('add_to_cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('delete_from_cart/<str:slug>/<str:cart_id>/', delete_from_cart, name='delete_from_cart'),
    path('change_qty/<str:slug>/<str:cart_id>/', change_qty, name='change_qty'),
    path('checkout/', checkout, name='checkout'),
    path('checkout_post/', checkout_post, name='checkout_post'),
    path('blog/', blog, name='blog'),
    path('blog/<str:slug>/', blog_detail, name='blog_detail'),
]

rif5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField('Изображение', upload_to='categories', null=True, blank=True)
    description = models.CharField('Описание', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('category_detail', args=[str(self.slug)])


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название продукта')
    category = models.ForeignKey('SubCategory', on_delete=models.PROTECT, verbose_name='Категория продукта')
    description = models.TextField(max_length=2000, verbose_name='Описание продукта')
    image = models.ImageField(verbose_name='Изображение')
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='Цена продукта')
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.slug)])


class CartProduct(models.Model):
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.PROTECT, related_name='related_products')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар в корзине', null=True)
    qty = models.PositiveIntegerField(default=1, verbose_name='Количество')
    total_price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='Общая стоимость', default=0)

    def __str__(self):
        return f'Продукт: {self.product.name} (для корзины)'

    class Meta:
        verbose_name = 'Товар для корзины'
        verbose_name_plural = 'Товары для корзины'

    def save(self, *args, **kwargs):
        self.total_price = self.product.price * self.qty
        return super(CartProduct, self).save()


class Cart(models.Model):
    total_products = models.PositiveIntegerField(default=0, verbose_name='Товаров')
    final_price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='Общая цена', default=0)
    phone = models.CharField(max_length=20, verbose_name='Телефон', blank=True)
    address = models.CharField(max_length=500, verbose_name='Адрес', blank=True)
    name = models.CharField(max_length=250, verbose_name='Имя', default='User', blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания', blank=True, null=True)
    finished = models.BooleanField(default=False, verbose_name='Завершён', blank=True)
    comment = models.TextField(max_length=1000, blank=True, null=True, verbose_name='Комментарии')
    products = models.ForeignKey(CartProduct, blank=True, verbose_name='Товары в корзине',
                                      related_name='related_cart', on_delete=models.PROTECT, null=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def final_price_def(self):
        self.final_price = 0
        for item in CartProduct.objects.filter(cart=self.id):
            self.final_price += item.total_price
        self.save()

    def total_products_def(self):
        self.total_products = 0
        for item in CartProduct.objects.filter(cart=self.id):
            self.total_products += item.qty
        self.save()

class Customer(models.Model):
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    address = models.CharField(max_length=500, verbose_name='Адрес')
    name = models.CharField(max_length=250, verbose_name='Имя', default='User')

    def __str__(self):
        return f'Покупатель: {self.name}'

    class Meta:
        verbose_name = 'Покупатель'
        verbose_name_plural = 'Покупатели'


class CarouselCategory(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Слайдеры'
        verbose_name_plural = 'Слайдеры'


class CarouselImages(models.Model):
    name = models.CharField(max_length=250, verbose_name='Название')
    category = models.ForeignKey(CarouselCategory, verbose_name='Категория', on_delete=models.PROTECT)
    image = models.ImageField(verbose_name='Изображение')
    is_active = models.BooleanField(default=True, verbose_name='Активное')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Изображение для слайдера'
        verbose_name_plural = 'Изображения для слайдера'


class Blog(models.Model):
    title = models.CharField('Заголовок', max_length=250)
    text = models.TextField('Текст', max_length=2000)
    short_text = models.TextField('Описание', max_length=500, blank=True, null=True)
    image_large = models.ImageField('Большое изображение', upload_to='img/blog/large')
    image_small = models.ImageField('Маленькое изображение', upload_to='img/blog/small')
    slug = models.SlugField(unique=True)
    date = models.DateField('Дата', default=timezone.now)
    published = models.BooleanField('Опубликовано', default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блог'

    def get_absolute_url(self):
        return reverse('blog_detail', args=[str(self.slug)])


class Promo(models.Model):
    name = models.CharField('Название', max_length=250)
    text = models.TextField('Текст', max_length=2000)
    short_text = models.TextField('Короткий текст', max_length=1000)
    image = models.ImageField('Изображение', upload_to='promo')
    small_image = models.ImageField('Превью', upload_to='promo')
    slug = models.SlugField(unique=True)
    date = models.DateField('Дата', default=timezone.now)
    published = models.BooleanField('Опубликовано', default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Акция'
        verbose_name_plural = 'Акции'


class SubCategory(models.Model):
    name = models.CharField('Название', max_length=250)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField('Изображение', upload_to='categories', null=True, blank=True)
    description = models.TextField('Описание', max_length=1000, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name='Категория')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'

    def get_absolute_url(self):
        return reverse('sub_category_detail', args=[str(self.slug)])

mainapp/forms.py
from django import forms


class CartForm(forms.Form):
    name = forms.CharField(max_length=100, label='Ваше имя')
    phone = forms.IntegerField(label='Номер телефона')
    address = forms.CharField(max_length=1000, label='Адрес для доставки')

mainapp/views.py
from django.core.mail import send_mail
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import View

from .models import *
from .forms import CartForm


def view(request):
    if 'cart_pk' not in request.session:
        cart = Cart.objects.create()
        cart_pk = cart.pk
        cart.save()
        request.session['cart_pk'] = cart_pk
    cart = Cart.objects.get(pk=request.session['cart_pk'])
    products = Product.objects.all()
    images = CarouselImages.objects.filter(category__name='На главной', is_active=True)
    context = {
        'products': products,
        'category': Category.objects.all(),
        'cart_product_count': cart.total_products,
        'images': images,
    }
    return render(request, 'base.html', context)


def product_view(request, slug):
    if 'cart_pk' not in request.session:
        cart = Cart.objects.create()
        cart_pk = cart.pk
        cart.save()
        request.session['cart_pk'] = cart_pk
    cart = Cart.objects.get(pk=request.session['cart_pk'])
    category = Category.objects.all()
    product = Product.objects.filter(slug=slug).first()
    context = {
        'cart_product_count': cart.total_products,
        'product': product,
        'category': category,
    }
    return render(request, 'product_detail.html', context)


def category_view(request, slug):
    if 'cart_pk' not in request.session:
        cart = Cart.objects.create()
        cart_pk = cart.pk
        cart.save()
        request.session['cart_pk'] = cart_pk
    cart = Cart.objects.get(pk=request.session['cart_pk'])
    category = Category.objects.all()
    promo = Promo.objects.all()
    subcategory = SubCategory.objects.filter(category__slug=slug)
    selected_category = Category.objects.filter(slug=slug).first()
    context = {
        'subcategory': subcategory,
        'category': category,
        'selected_category': selected_category,
        'cart_product_count': cart.total_products,
        'promo': promo,
    }
    return render(request, 'category.html', context)


def sub_category_view(request, slug):
    if 'cart_pk' not in request.session:
        cart = Cart.objects.create()
        cart_pk = cart.pk
        cart.save()
        request.session['cart_pk'] = cart_pk
    cart = Cart.objects.get(pk=request.session['cart_pk'])
    category = Category.objects.all()
    promo = Promo.objects.all()
    products = Product.objects.filter(category__slug=slug)
    selected_sub_category = SubCategory.objects.filter(slug=slug).first()
    context = {
        'selected_sub_category': selected_sub_category,
        'cart_product_count': cart.total_products,
        'promo': promo,
        'products': products,
        'category': category,
    }
    print(selected_sub_category.category)
    return render(request, 'sub_category.html', context)


def cart_view(request):
    if 'cart_pk' not in request.session:
        cart = Cart.objects.create()
        cart_pk = cart.pk
        cart.save()
        request.session['cart_pk'] = cart_pk
    cart = Cart.objects.get(pk=request.session['cart_pk'])
    category = Category.objects.all()
    products = CartProduct.objects.filter(cart=cart)
    cart.final_price_def()
    cart.total_products_def()
    context = {
        'category': category,
        'products': products,
        'cart_product_count': cart.total_products,
        'cart': cart,
    }
    return render(request, 'cart.html', context)


class AddToCartView(View):
    def get(self, request, *args, **kwargs):
        product_slug = kwargs.get('slug')
        product = Product.objects.get(slug=product_slug)
        cart = Cart.objects.get(pk=request.session['cart_pk'])
        CartProduct.objects.get_or_create(cart=cart, product=product)
        return HttpResponseRedirect('/cart/')


def delete_from_cart(request, slug, cart_id):
    CartProduct.objects.get(cart__id=cart_id, product__slug=slug).delete()
    return HttpResponseRedirect('/cart/')


def change_qty(request, slug, cart_id):
    product = CartProduct.objects.get(cart__id=cart_id, product__slug=slug)
    product.qty = int(request.POST.get('qty'))
    product.save()
    return HttpResponseRedirect('/cart/')


def checkout(request):
    form = CartForm(request.POST or None)
    cart = Cart.objects.get(pk=request.session['cart_pk'])
    context = {
        'category': Category.objects.all(),
        'cart_product_count': cart.total_products,
        'form': form,
    }
    return render(request, 'checkout.html', context)


def checkout_post(request):
    form = CartForm(request.POST or None)
    if form.is_valid():
        cart = Cart.objects.get(pk=request.session['cart_pk'])
        cart.name = form.cleaned_data['name']
        cart.phone = form.cleaned_data['phone']
        cart.address = form.cleaned_data['address']
        cart.save()
        send_mail('Новый заказ', 'Ура, новый заказ с сайта', 'trash@smartbit45.ru', ('crash-em@mail.ru', ))
    return HttpResponseRedirect('/')


def home(request):
    if 'cart_pk' not in request.session:
        cart = Cart.objects.create()
        cart_pk = cart.pk
        cart.save()
        request.session['cart_pk'] = cart_pk
    cart = Cart.objects.get(pk=request.session['cart_pk'])
    products = Product.objects.all()
    promo = Promo.objects.all()
    images = CarouselImages.objects.filter(category__name='На главной', is_active=True)
    blog = Blog.objects.all()[:5]
    context = {
        'products': products,
        'category': Category.objects.all(),
        'cart_product_count': cart.total_products,
        'images': images,
        'promo': promo,
        'blog': blog,
    }
    return render(request, 'home.html', context)


def blog(request):
    if 'cart_pk' not in request.session:
        cart = Cart.objects.create()
        cart_pk = cart.pk
        cart.save()
        request.session['cart_pk'] = cart_pk
    cart = Cart.objects.get(pk=request.session['cart_pk'])
    promo = Promo.objects.all()
    blog = Blog.objects.all()
    context = {
        'category': Category.objects.all(),
        'cart_product_count': cart.total_products,
        'promo': promo,
        'blog': blog,
    }
    return render(request, 'blog.html', context)


def blog_detail(request, slug):
    if 'cart_pk' not in request.session:
        cart = Cart.objects.create()
        cart_pk = cart.pk
        cart.save()
        request.session['cart_pk'] = cart_pk
    cart = Cart.objects.get(pk=request.session['cart_pk'])
    promo = Promo.objects.all()
    blog = Blog.objects.filter(slug=slug).first()
    context = {
        'category': Category.objects.all(),
        'cart_product_count': cart.total_products,
        'promo': promo,
        'blog': blog,
    }
    return render(request, 'blog_detail.html', context)

mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <style>
        body {
            padding-top: 56px;
        }
    </style>
    <script>var clicky_site_ids = clicky_site_ids || []; clicky_site_ids.push(101311623);</script>
    <script async src="//static.getclicky.com/js"></script>
</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-pill badge-danger">{{ cart_product_count }}</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <h1 class="my-4">Shop Name</h1>
            <div class="list-group">
                {% for item in category %}
                <a href="{{ item.get_absolute_url }}" class="list-group-item">{{ item.name }}</a>
                {% endfor %}
            </div>
        </div>
        <!-- /.col-lg-3 -->
        <div class="col-lg-9">
            {% block carousel %}
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for item in images %}
                        {% if forloop.first %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        {% else %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter }}"></li>
                        {% endif %}
                    {% endfor %}
                </ol>
                <div class="carousel-inner" role="listbox">
                    {% for item in images %}
                        {% if forloop.first %}
                            <div class="carousel-item active">
                                <img class="d-block img-fluid" src="{{ item.image.url }}" alt="First slide">
                            </div>
                        {% else %}
                            <div class="carousel-item">
                                <img class="d-block img-fluid" src="{{ item.image.url }}" alt="Second slide">
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            {% endblock carousel %}
            {% block content %}
            <div class="row">
                {% for item in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="{{ item.get_absolute_url }}"><img class="card-img-top" src="{{ item.image.url }}" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ item.name }}</a>
                            </h4>
                            <h5>{{ item.price }} ₽</h5>
                            <p class="card-text">{{ item.description }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- /.row -->
            {% endblock content %}
        </div>
        <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/blog.html
{% load static %}

{% include 'head.html' %}

<body>
{% include 'header.html' %}

<!-- Categories Section Begin -->
<section class="categories categories-grid spad">
  <div class="categories__post">
    <div class="container">
      <div class="categories__grid__post">
        <div class="row">
          <div class="col-lg-8 col-md-8">
            <div class="breadcrumb__text">
              <h2>Блог</h2>
              <div class="breadcrumb__option">
                <a href="{% url 'home' %}">Главная</a>
                <span>Блог</span>
              </div>
            </div>
            <div class="row">
              {% for item in blog %}
                <div class="col-lg-6 col-md-6 col-sm-6">
                  <div class="categories__post__item">
                    <div class="categories__post__item__pic small__item set-bg"
                         data-setbg="{{ item.image_small.url }}">
                      <div class="post__meta">
                        <h4>{{ item.date|date:'d' }}</h4>
                        <span>{{ item.date|date:'M' }}</span>
                      </div>
                    </div>
                    <div class="categories__post__item__text">
                      <span class="post__label">Recipe</span>
                      <h3><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></h3>
                      <ul class="post__widget">
                        <li>by <span>Admin</span></li>
                        <li>3 min read</li>
                        <li>20 Comment</li>
                      </ul>
                      <p>{{ item.short_text }}</p>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
          {% include 'sidebar.html' %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Categories Section End -->

<!-- Footer Section Begin -->
{% include 'footer.html' %}
<!-- Footer Section End -->

mainapp/templates/blog_detail.html
{% load static %}

{% include 'head.html' %}

<body>
{% include 'header.html' %}

<!-- Single Post Section Begin -->
<section class="single-post spad">
  <div class="single-post__hero set-bg"
       data-setbg="{{ blog.image_large.url }}"></div>
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-8">
        <div class="single-post__title">
          <div class="single-post__title__meta">
            <h2>{{ blog.date|date:'d' }}</h2>
            <span>{{ blog.date|date:'M' }}</span>
          </div>
          <div class="single-post__title__text">
            <ul class="label">
              <li>Vegan</li>
              <li>Desserts</li>
            </ul>
            <h2>{{ blog.title }}</h2>
            <ul class="widget">
              <li>by Admin</li>
              <li>3 min read</li>
              <li>20 Comment</li>
            </ul>
          </div>
        </div>
        <div class="single-post__social__item">
          <ul>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
            <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
          </ul>
        </div>
        <div class="single-post__top__text">
          <p>{{ blog.text|safe }}</p>
        </div>
        <div class="single-post__tags">
          <a href="#">Food</a>
          <a href="#">Vegan</a>
          <a href="#">Tomato</a>
          <a href="#">Weightloss</a>
        </div>
        <div class="single-post__comment">
          <div class="widget__title">
            <h4>03 Comment</h4>
          </div>
          <div class="single-post__comment__item">
            <div class="single-post__comment__item__pic">
              <img src="img/categories/single-post/comment/comment-1.jpg" alt="">
            </div>
            <div class="single-post__comment__item__text">
              <h5>Brandon Kelley</h5>
              <span>15 Aug 2017</span>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore
                magnam.</p>
              <ul>
                <li><a href="#"><i class="fa fa-heart-o"></i></a></li>
                <li><a href="#"><i class="fa fa-share-square-o"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="single-post__comment__item single-post__comment__item--reply">
            <div class="single-post__comment__item__pic">
              <img src="img/categories/single-post/comment/comment-2.jpg" alt="">
            </div>
            <div class="single-post__comment__item__text">
              <h5>Brandon Kelley</h5>
              <span>15 Aug 2017</span>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore
                magnam.</p>
              <ul>
                <li><a href="#"><i class="fa fa-heart-o"></i></a></li>
                <li><a href="#"><i class="fa fa-share-square-o"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="single-post__comment__item">
            <div class="single-post__comment__item__pic">
              <img src="img/categories/single-post/comment/comment-3.jpg" alt="">
            </div>
            <div class="single-post__comment__item__text">
              <h5>Brandon Kelley</h5>
              <span>15 Aug 2017</span>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore
                magnam.</p>
              <ul>
                <li><a href="#"><i class="fa fa-heart-o"></i></a></li>
                <li><a href="#"><i class="fa fa-share-square-o"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="single-post__leave__comment">
          <div class="widget__title">
            <h4>Leave a comment</h4>
          </div>
          <form action="#">
            <div class="input-list">
              <input type="text" placeholder="Name">
              <input type="text" placeholder="Email">
              <input type="text" placeholder="Website">
            </div>
            <textarea placeholder="Message"></textarea>
            <button type="submit" class="site-btn">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Single Post Section End -->

<!-- Footer Section Begin -->
{% include 'footer.html' %}
<!-- Footer Section End -->

mainapp/templates/category_detail.html
{% extends 'base.html' %}
{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">{{ selected_category }}</a></li>
        </ol>
    </nav>
    <div class="row">
        {% for item in product %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="#"><img class="card-img-top" src="{{ item.image.url }}" alt=""></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{{ item.get_absolute_url }}">{{ item.name }}</a>
                        </h4>
                        <h5>{{ item.price }} ₽</h5>
                        <p class="card-text">{{ item.description }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}

mainapp/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form action="{% url 'checkout_post' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Заказать" class="btn btn-success">
    </form>
{% endblock content %}

mainapp/templates/sidebar.html
<div class="col-lg-4 col-md-4">
          <h2 style="text-align: center; margin: 30px 30px">Акции</h2>
          <div class="sidebar__item">
            {% for item in promo %}
              <div class="sidebar__about__item">
                <div class="sidebar__item__title">
                  <h6>{{ item.name }}</h6>
                </div>
                <img src="{{ item.small_image.url }}" alt="">
                <p>{{ item.short_text }}</p>
                <a href="{{ item.get_absolute_url }}" class="primary-btn">Подробнее</a>
              </div>
            {% endfor %}
            <div class="sidebar__follow__item">
              <div class="sidebar__item__title">
                <h6>Соц цети</h6>
              </div>
              <div class="sidebar__item__follow__links">
                <a href="#"><i class="fa fa-vk"></i></a>
                <a href="#"><i class="fa fa-youtube-play"></i></a>
                <a href="#"><i class="fa fa-instagram"></i></a>
                <a href="#"><i class="fa fa-envelope-o"></i></a>
              </div>
            </div>
            <div class="sidebar__item__categories">
              <div class="sidebar__item__title">
                <h6>Меню</h6>
              </div>
              <ul>
                {% for item in category %}
                  <li><a href="#">{{ item.name }} <span>{{ item.product_set.count }}</span></a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>